### ISSUE TITLE
特征表格和非细菌过滤步骤的小疑问

### ISSUE THREAD

**Issue by sharkLoc** [YongxinLiu/EasyAmplicon#10]
您好！
我有一个疑问，就是步骤5.1生成特征表步的部分和步骤5.2去除质体和非细菌 Remove plastid and non-Bacteria的部分，这两步的顺序可以交换么？因为我看到5.1中已经生成了特征表格，在5.2中又对otu序列做了过滤(剔除非细菌等序列)，然后根据过滤的out序列id去筛选上一步中的特征表格。能否先做非细菌序列剔除，然后直接生成最后的OTU表格？

谢谢！

**Comment by YongxinLiu** [comment]
不可以，基于表格筛选非常快，优势明显。先筛选序列，你需要自己设计过滤方案
