### ISSUE TITLE
Error in data.frame(..., check.names = FALSE) :    arguments imply differing number of rows: 0, 18

### ISSUE THREAD

**Issue by LIYIN2** [YongxinLiu/EasyAmplicon#12]
p = alpha_boxplot(alpha_div, index = opts$alpha_index, metadata, groupID = opts$group ),这一步报错，请问有什么解决方法

**Comment by YongxinLiu** [comment]
Run it in Diversity.Rmd, keep all code is running, it's OK.
The error may found with your input data is abnormal, please check.
