### ISSUE TITLE
unable to download r packages quick install, for overseas user

### ISSUE THREAD

**Issue by NabiilahArdini** [YongxinLiu/EasyAmplicon#14]
Hello. 

I want to quick install the R packages (dependencies) but unable to access the Baidu (overseas user). Can you upload it in other sharing platform that is easier to access/provide script on what packages to install/list the packages that we need?

Thanks!

**Comment by YongxinLiu** [comment]
Using filezilla visiting FTP: download.nmdc.cn in anonymous
