### ISSUE TITLE
关于图片保存问题

### ISSUE THREAD

**Issue by panzhuoddv** [YongxinLiu/EasyAmplicon#5]
刘老师您好，
        十分感谢您提供了非常有用的代码和教程。
        在您写的pipline中，图片保存格式均为pdf，我尝试将其保存为其他格式图片，打开源码后，发现ggsave的参数如下
        
![1652670497(1)](https://user-images.githubusercontent.com/72605876/168513731-14b052a6-bcc8-4011-b76a-7aaaf6b78cd6.png)
       其中我尝试直接把后缀改为.png或其它图片格式，但是一直不成功，主程序会报错
![1652670860(1)](https://user-images.githubusercontent.com/72605876/168513873-7c9d4702-e1fe-422c-bb2f-d07e078ce43f.png)
       不知道有没有办法直接将其保存为图片格式。

       此外，在您分享的视频中，大概占到了pipeline内容的一半流程，不知道您方不方便分享余下内容，比如QIIME 2分析流程之类的内容。

**Comment by YongxinLiu** [comment]
PDF是最适合出版的格式，而且可编辑。建议需要可在截图，或用Adobe illustrator将PDF另存为任意格式。QIIME的流程也有的，就有qiime2文件夹中。
