### ISSUE TITLE
Problems with "alpha_boxplot" - ​EasyAmplicon pipeline

### ISSUE THREAD

**Issue by laboratorist** [YongxinLiu/EasyAmplicon#7]
Hi, 

I worked through all the steps in the pipeline.sh file to alpha diversity step. I was trying the function `alpha_boxplot` but I have encountered some difficulties and I am hoping that someonecan help!

The specific error is:

    Error in alpha_boxplot(alpha_div, index = opts$alpha_index, metadata, : could not find function "alpha_boxplot

I thought I need to install the amplicon package and I tried using the code devtools::install_github("microbiota/amplicon") but encountered this error:

    Error in file(filename, "r", encoding = encoding) : cannot open the connection Calls: source -> file In addition: Warning message: In file(filename, "r", encoding = encoding) : cannot open file 'renv/activate.R': No such file or directory Execution halted

Any help is highly appreciated!

Thanks,

**Comment by manik-123** [comment]
For me it worked, maybe because i coped all the packages in R... you can try.
