### ISSUE TITLE
usearch.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by manik-123** [YongxinLiu/EasyAmplicon#8]
Hi,
When i run 
usearch -unoise3 temp/uniques.fa -minsize 10 \
      -zotus temp/zotus.fa
I am getting the error :
C:/Users/Manik/OneDrive/Desktop/EasyMicrobiome/win/usearch.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory...
Can you please help.

**Comment by YongxinLiu** [comment]
I never meet this problem. Please try in another computer, may work. Thousands of people use it work well.

**Comment by gennuowang** [comment]
> Hi, When i run usearch -unoise3 temp/uniques.fa -minsize 10 -zotus temp/zotus.fa I am getting the error : C:/Users/Manik/OneDrive/Desktop/EasyMicrobiome/win/usearch.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory... Can you please help.
hello @manik-123, I also have the same problem as you. Did you solve it? Thank you in advance.

**Comment by gennuowang** [comment]
> > Hi, When i run usearch -unoise3 temp/uniques.fa -minsize 10 -zotus temp/zotus.fa I am getting the error : C:/Users/Manik/OneDrive/Desktop/EasyMicrobiome/win/usearch.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory... Can you please help.
> > hello @manik-123, I also have the same problem as you. Did you solve it? Thank you in advance.


> Yes, It is solved. I downloaded usearch.exe and replaced it....

hello @manik-123, where did you download usearch.exe? I downloaded it (32-bit) from http://www.drive5.com/usearch/ (official) and the GitHub of easyamplicon, but both did not work. Thank you.

**Comment by manik-123** [comment]
Yes, the same site, but I forgot which version I downloaded.

**Comment by gennuowang** [comment]
> Yes, the same site, but I forgot which version I downloaded.

hi @manik-123, would you mind sharing the usearch.exe that you downloaded with me? I tried many ways, but it still did not work. Thank you very much.

**Comment by manik-123** [comment]
can you share me ur email?

**Comment by gennuowang** [comment]
> can you share me ur email?

yes, gennuo2021@gmail.com. Thank you very much!

**Comment by manik-123** [comment]
Sorry the file is unable to attach, is there any other way....like WeChat or other
